### ISSUE TITLE
Download Link for Pre-trained model is broken

### ISSUE THREAD

**Issue by mrFahrenhiet** [leftthomas/GatedSCNN#1]
Hello @leftthomas!
Thank you for this amazing implementation. I was facing some issue with the download link of the pre-trained model you provided in the readme section of the repository. Can you please check that link, it seems to be broken.

**Comment by leftthomas** [comment]
It's not broken, it's a Baidu website.

**Comment by pan111-pp** [comment]
> 

Excuse me, what is the extraction code

**Comment by leftthomas** [comment]
@pan111-pp , dsjb, readme has shown this.
